# This compose file is for local development only
services:
  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env

    image: nginx-server:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.template
      - ./nginx/mock_letsencrypt:/etc/letsencrypt:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - network1

  location:
    build:
      context: ./location
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.local
    image: how-to-sea-location
    ports:
      - '8888:8000'
    working_dir: /app_dev
    command: ["gunicorn", "--config", "/app_dev/gunicorn.conf.py", "app:app"]
    volumes:
    - ./location:/app_dev
    networks:
      - network1
      
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.local
    image: how-to-sea-auth
    ports:
      - '8889:8000'
      - '50051:50051'
    working_dir: /app_dev
    command: ["./start.sh"]
    volumes:
      - ./auth:/app_dev
    networks:
      - network1

networks:
  network1:
    name: how-to-sea
    external: true