# This compose file is for local development only
services:
  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-server:latest
    env_file:
      - './nginx/.env'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.template
      - ./nginx/mock_letsencrypt:/etc/letsencrypt:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - network1

  location:
    build:
      context: ./location
      dockerfile: Dockerfile
    image: how-to-sea-location
    environment:
      - MONGODB_PW=${MONGODB_PW}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_DB=${MONGODB_DB}
    volumes:
    - ./location:/app_dev
    ports:
      - '8888:8000'
    command: ["gunicorn", "--config", "/app_dev/gunicorn.conf.py", "app:app"]
    networks:
      - network1
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: how-to-sea-auth
    ports:
      - '8889:8000'
    env_file:
      - './auth/.env.local'
    working_dir: /app_dev
    command: ["gunicorn", "--config", "/app_dev/gunicorn.conf.py", "app:app"]
    volumes:
      - ./auth:/app_dev
    networks:
      - network1

networks:
  network1:
    name: how-to-sea
    external: true